FROM centos:6
MAINTAINER Matthew Endsley <matt@carbongames.com>

# Template to add a build user with a matching uid to the developer
RUN adduser --no-create-home --system --uid %uid% build

RUN yum install -y gcc gcc-c++ make openssl-devel
RUN yum localinstall -y http://dl.fedoraproject.org/pub/epel/6/x86_64/libev-4.03-3.el6.x86_64.rpm
RUN yum localinstall -y http://dl.fedoraproject.org/pub/epel/6/x86_64/libev-devel-4.03-3.el6.x86_64.rpm

USER build
