FROM centos:7
MAINTAINER Matthew Endsley <matt@carbongames.com>

# Template to add a build user with a matching uid to the developer
RUN adduser --no-create-home --system --uid %uid% build

RUN yum install -y gcc gcc-c++ make openssl-devel
RUN yum install -y libev-devel

USER build
